name: "linting & testing"

on:
  push:
    branches:
      - main
    paths:
      - "lib/**"
      - "spec/**"
      - ".github/workflows/main.yml"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      APPRAISAL_NAME: rack_only
      BUNDLE_GEMFILE: ./gemfiles/rack_only.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-use-ruby-ubuntu-latest-2.7-rack_only-${{ hashFiles(format('{0}.lock', env.BUNDLE_GEMFILE)) }}
          restore-keys: |
            bundle-use-ruby-ubuntu-latest-2.7-rack_only
      - name: bundle install
        run: |
          gem update --system
          bundle config deployment true
          bundle config path vendor/bundle
          bundle install --jobs 4
      - name: "Run rubocop"
        run: |
          bin/rubocop
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        appraisal_name: [rack_only, rails_6_0, rails_6_1]
        ruby: [2.7, 3.0]
    env:
      APPRAISAL_NAME: ${{ matrix.appraisal_name }}
      BUNDLE_GEMFILE: ${{ format('./gemfiles/{0}.gemfile', matrix.appraisal_name) }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-use-ruby-ubuntu-latest-${{ matrix.ruby }}-${{ env.APPRAISAL_NAME }}-${{ hashFiles(format('{0}.lock', env.BUNDLE_GEMFILE)) }}
          restore-keys: |
            bundle-use-ruby-ubuntu-latest-${{ matrix.ruby }}-${{ env.APPRAISAL_NAME }}
      - name: bundle install
        run: |
          gem update --system
          bundle config deployment true
          bundle config path vendor/bundle
          bundle install --jobs 4
      - name: "Run RSpec"
        run: |
          bin/rspec
