name: "linting & testing"

on:
  push:
    branches:
      - main
    paths:
      - "gemfiles/**"
      - "lib/**"
      - "spec/**"
      - ".github/workflows/main.yml"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: ruby-4.0.1
      RUBOCOP_CACHE_ROOT: tmp/rubocop
      APPRAISAL_NAME: rack_3
      BUNDLE_GEMFILE: ./gemfiles/rack_3.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - uses: actions/cache@v5
        env:
          DEPENDENCIES_HASH: ${{ hashFiles('.rubocop.yml', '.rubocop_todo.yml', format('{0}.lock', env.BUNDLE_GEMFILE)) }}
        with:
          path: ${{ env.RUBOCOP_CACHE_ROOT }}
          key: rubocop-${{ runner.os }}-${{ env.RUBY_VERSION }}-${{ env.DEPENDENCIES_HASH }}-${{ github.ref_name == github.event.repository.default_branch && github.run_id || 'default' }}
          restore-keys: |
            rubocop-${{ runner.os }}-${{ env.RUBY_VERSION }}-${{ env.DEPENDENCIES_HASH }}-
      - name: "Run rubocop"
        run: |
          bin/rubocop -f github
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        appraisal_name: [jwt_2, jwt_3, rack_2, rack_3, rails_7_1, rails_7_2, rails_8_0, rails_8_1]
        ruby: [3.4.7, 4.0.1]
    env:
      APPRAISAL_NAME: ${{ matrix.appraisal_name }}
      BUNDLE_GEMFILE: ${{ format('./gemfiles/{0}.gemfile', matrix.appraisal_name) }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: "Run RSpec"
        run: |
          bin/rspec
